### PR TITLE
Add news feature

### PR DESCRIPTION
**Pull request by nicudy**
The add news feature is complete.
Tests will be added later.

### CODE REVIEW

**Review by kianapaz — APPROVED** [review]

**Comment by AntonNiko** [comment]
We should add selenium tests for this feature to make sure we validate our user stories.

**Review by AntonNiko — CHANGES_REQUESTED** [review]
Add selenium tests

**Comment by nicudy** [comment]
> Add selenium tests

Hey Anton, tests are added if you can check it out now!

**Review by AntonNiko — APPROVED** [review]
Looks great, I pushed a commit fixing failing selenium tests so should be good now.

**Pull request merged**
